spring:
  profiles:
    include: SECRET-KEY # SECRET-KEY 프로파일 활성화

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/${database-name}
    username: ${database-username}
    password: ${database-password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging.level:
  org.hibernate.SQL: debug
